# This is a basic workflow to help you get started with Actions

name: github-actions-run-test-on-PR CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      -  'main'
      -  'develop'
  pull_request:
    branches: 
      -  'main'
      -  'develop'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up JDK v11
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 11.0.11
          distribution: adopt
      - name: Setup MySQL
  # You may pin to the exact commit or the version.
  # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
        uses: mirromutth/mysql-action@v1.1
        with:
          # Version of MySQL to use
          mysql version: 8.0.30
          # MYSQL_ROOT_PASSWORD - root superuser password
          mysql root password: test1234
          # MYSQL_DATABASE - name for the default database that is created
          mysql database: email
          # MYSQL_USER - create the specified user with superuser power for created database
          mysql user: root
          # MYSQL_PASSWORD - specified superuser password which user is power for created database
          mysql password: test1234
            
      - name: Maven Cache
        uses: skjolber/maven-cache-github-action@v1.1
        with:
          step: restore

      - name: extract version for pom.xml
        run: echo "VERSION=$(grep -oPm2 "(?<=<version>)[^<]+" pom.xml | sed -n 2p)" >> $GITHUB_ENV
      
      - name: Spring Boot Build with Maven
        run: mvn package -Dskip.test=true
        
      - name: Maven Cache
        uses: skjolber/maven-cache-github-action@v1.1
        with:
          step: save
          
      - name: Current Time
        uses: gerred/current-time@v1.0.0
        id: current-time
        
      - name: get current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        run: echo $TIME
